// Mocks generated by Mockito 5.4.4 from annotations
// in lokalise_flutter_sdk/test/src/ota/domain/services/message_lookup_proxy_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:intl/src/intl_helpers.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MessageLookup].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageLookup extends _i1.Mock implements _i2.MessageLookup {
  MockMessageLookup() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void addLocale(
    String? localeName,
    Function? findLocale,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addLocale,
          [
            localeName,
            findLocale,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
