name: lokalise_flutter_sdk
description: Lokalise Flutter SDK over-the-air translations updates. This package provides new translations from lokalise.com without a new app release.
version: 1.3.2
homepage: https://developers.lokalise.com/docs/flutter-sdk

# On next major update:
#   Remove support for Dart 2 -> environment.sdk: ^3.0.0
#   Intl -> support only the lastes verion
#   Intl_translation -> support only the lastes version
#   logger -> support only the latest version
#   package_info_plus -> support only the latests versions

environment:
  sdk: ">=2.17.6 <4.0.0" # Remove support for Dart 2 on next major update
  flutter: ">=1.17.0"

dependencies:
  dart_style: ^2.0.0
  flutter:
    sdk: flutter
  intl: ">=0.17.0 <0.21.0" # Remove support for old versions on next major update (needed for Dart 2.17)
  intl_translation: ">=0.18.0 <0.21.0"
  yaml: ^3.0.0
  path: ^1.0.0
  petitparser: ">=4.0.0 <7.0.0" # Remove support for 4 and 5 on next major update
  logger: ">=1.0.0 <3.0.0" # Remove support for 1 on next major update
  shared_preferences: ^2.0.0
  http: ">=0.13.5 <2.0.0" # Remove support for old verions on next major update (needed for Dart 2)
  archive: ^3.0.0
  package_info_plus: ">=3.0.2 <9.0.0" # Remove support for old versions on next major update (needed for Dart 2.17)

dev_dependencies:
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.0.0

executables:
  gen-lok-l10n:

platforms:
  ios:
  android:
  macos:
  windows:
  linux:
  web:
